[build]
  publish = "_site"
  command = "npm run build-production"

[[plugins]]
package = "./plugins/keep-data-cache"

[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "https://alvaro-speed.netlify.app/*"
  to = "https://speed.alvaro.design/:splat"
  force = true
